services:
  - type: web
    name: spl-app-prod
    runtime: node
    plan: free
    buildCommand: npm install --production=false && npm run build
    startCommand: npm run db:push && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: PROD_DOMAIN
        value: splapp-prod.onrender.com
